services:
  external-x10Bot-redis:
    image: redis:latest
    ports:
      - "6300:6379"
    volumes:
      - x10-external-bot_redis_data:/data
    restart: always

  external-x10Bot-app:
    build: .
    image: x10-external-bot-app
    working_dir: /usr/src/app
    environment:
      - REDIS_HOST=external-x10Bot-redis
      - REDIS_PORT=6379
      - PGHOST=external-x10Bot-postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - external-x10Bot-redis
      - external-x10Bot-postgres
    restart: always

  external-x10Bot-postgres:
    image: postgres:15-alpine
    container_name: external-x10Bot-postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5400:5432"
    volumes:
      - x10-external-bot_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  x10-external-bot_redis_data:
  x10-external-bot_postgres_data: