services:
  prod-x10-redis:
    image: redis:latest
    container_name: prod-x10-redis
    ports:
      - "6400:6379"
    volumes:
      - prod-x10_redis_data:/data
    restart: always

  prod-x10-app:
    build: .
    image: prod-x10-app
    container_name: prod-x10-app
    working_dir: /usr/src/app
    environment:
      - REDIS_HOST=prod-x10-redis
      - REDIS_PORT=6379
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
      - REPORT_SERVICE_HOST=${REPORT_SERVICE_HOST}
      - BASE_PORT=${BASE_PORT}  
    depends_on:
      - prod-x10-redis
      - prod-x10-postgres
      - prod-x10-reporter
    restart: always

  prod-x10-postgres:
    image: postgres:15-alpine
    container_name: prod-x10-postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5500:5432"
    volumes:
      - prod-x10_postgres_data:/var/lib/postgresql/data
    restart: always

  prod-x10-reporter:
    build:
      context: .
      dockerfile: reportService.Dockerfile 
    image: prod-x10-reporter
    container_name: prod-x10-reporter
    ports:
      - "3300:3300"
    environment:
      - PORT=3300
    restart: always

volumes:
  prod-x10_redis_data:
  prod-x10_postgres_data: